config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/policy'
  get 'static_pages/terms'
  
  resources :guest_sessions, only: [:create]
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/index_room:id', to: 'rooms#index',as: 'index_room'
 
  get '/profile:id', to: 'users#profile',as: 'profile_user'
  get '/index:id', to: 'users#index',as: 'index'
  get '/follower:id', to: 'users#follower',as: 'follower'
  get '/following:id', to: 'users#following',as: 'following'
  get '/setting:id', to: 'users#setting',as: 'setting'
  get '/edit_prf:id', to: 'users#edit_prf',as: 'edit_prf'
  get '/favorite:id', to: 'users#favorite',as: 'favorite'
  get '/community_list:id', to: 'users#community_list',as: 'community_list'
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/send_message:id', to: 'rooms#send_message',as: 'send_message'
  get '/match:id', to: 'users#matcher',as: 'match'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms
  resources :messages, :only => [:create]
  resources :communities do
    resource :joins, only: [:create, :destroy]
  end
  
    get '/game:id', to: 'communities#game',as: 'game'
    get '/music:id', to: 'communities#music',as: 'music'
    get '/love:id', to: 'communities#love',as: 'love'
    get '/health:id', to: 'communities#health',as: 'health'
    get '/work:id', to: 'communities#work',as: 'work'
    get '/animal:id', to: 'communities#animal',as: 'animal'
    get '/sport:id', to: 'communities#sport',as: 'sport'
    get '/cafe:id', to: 'communities#cafe',as: 'cafe'
    get '/art:id', to: 'communities#art',as: 'art'
    get '/fashion:id', to: 'communities#fashion',as: 'fashion'
    get '/food:id', to: 'communities#food',as: 'food'
    get '/travel:id', to: 'communities#travel',as: 'travel'
    get '/info:id', to: 'communities#info',as: 'info'
  
  resources :users do
    member do
      get :following, :followers
    end
    get :joins, on: :collection
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    
  end
  
  def policy
    
  end
  
  def terms
    
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_footer.html.erb
<footer>
  <ul class="about-footer">
    <li><%= link_to '利用規約', '/static_pages/terms' , method: :get %></li>
    <li style="padding-left:30px;"><%= link_to 'プライバシーポリシー', '/static_pages/policy', method: :get %></li>
  </ul>
  <p style="text-align:center; padding-left:30px;">Copyright © 2021 Hayata Aoki All Rights Reserved.</p>
</footer>

app/views/static_pages/_header.html.erb
<header class="navbar">
    <div class="container logo">
         <nav>
            <i class="fas fa-gem fa-2x"></i><%= link_to ' RailsApp', root_path ,{style: "font-size:2.2em; padding-right:2em;"} %>
                <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to '新規登録', '/users/new',{class: "btn btn--signup2"} %></li>
                  <li style="padding-left:15px;"><%= link_to 'ログインする', '/sessions/new',{class: "btn btn--signup"} %></li>
                </ul>
          </nav>
     </div>
</header>

app/views/static_pages/_header.thml.erb
<header class="navbar">
    <div class="container logo">
         <nav>
            <i class="fas fa-gem fa-2x"></i><%= link_to ' RailsApp', '#',{style: "font-size:2.2em; padding-right:2em;"} %>
                <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to '新規登録', '/users/new',{class: "btn btn--signup2"} %></li>
                  <li style="padding-left:15px;"><%= link_to 'ログインする', '/sessions/new',{class: "btn btn--signup"} %></li>
                </ul>
          </nav>
     </div>
</header>

app/views/static_pages/home.html.erb
<%= render 'static_pages/header' %>
    
<div class="small-heading", style="text-align: center; font-weight: bolder; font-size: 40px;">
       <div style="color: #14305c;">    
          <p>マッチングアプリで</p>
          <p style="padding-top: 1%;">人生のパートナーを見つけよう</p>
       </div>
       
   <i class="far fa-heart fa-heart2"></i>
</div>

<div class="button-contents">
    <div><%= button_to 'ゲストログイン', guest_sessions_path, method: :post,class: "today shadow" %></div>
</div>

<%= render 'static_pages/footer' %>
   

   

app/views/static_pages/policy.html.erb
<%= render 'static_pages/header' %>

<div class="container" style="max-width: 900px;">
        <div class="card bg-paper p-4 my-4">
            <div class="card-body">
                <h3>
                    プライバシーポリシー
                </h3>
                <div class="card-text">
                    <p>
                        よんで運営者（以下、「当社」といいます。）は、本ウェブサイト上で提供するサービス（以下、「本サービス」といいます。）における、ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。
                    </p>
                </div>
            </div>
        <br>
            <div class="card-body mb-4">
                <h4 class="card-title">
                    第1条（個人情報）
                </h4>
                <div class="card-text">
                    <p>
                        「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報及び容貌、指紋、声紋にかかるデータ、及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。
                    </p>
                </div>
            </div>
        <br>
            <div class="card-body mb-4">
                <h4 class="card-title">
                    第2条（個人情報の収集方法）
                </h4>
                <div class="card-text">
                    <p>
                        当社は、ユーザーが利用登録をする際に氏名、生年月日、住所、電話番号、メールアドレス、銀行口座番号、クレジットカード番号、運転免許証番号などの個人情報をお尋ねすることがあります。また、ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を、当社の提携先（情報提供元、広告主、広告配信先などを含みます。以下、｢提携先｣といいます。）などから収集することがあります。
                    </p>
                </div>
            </div>
        <br>
            <div class="card-body mb-4">
                <h4 class="card-title">
                    第3条（個人情報を収集・利用する目的）
                </h4>
                <div class="card-text">
                    <p>
                        当社が個人情報を収集・利用する目的は、以下のとおりです。
                    </p>
                    <div class="ml-2">
                        <p>
                            1. 当社サービスの提供・運営のため
                        </p>
                        <p>
                            2. ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
                        </p>
                        <p>
                            3. ユーザーが利用中のサービスの新機能、更新情報、キャンペーン等及び当社が提供する他のサービスの案内のメールを送付するため
                        </p>
                        <p>
                            4. メンテナンス、重要なお知らせなど必要に応じたご連絡のため
                        </p>
                        <p>
                            5. 利用規約に違反したユーザーや、不正・不当な目的でサービスを利用しようとするユーザーの特定をし、ご利用をお断りするため
                        </p>
                        <p>
                            6. ユーザーにご自身の登録情報の閲覧や変更、削除、ご利用状況の閲覧を行っていただくため
                        </p>
                        <p>
                            7. 有料サービスにおいて、ユーザーに利用料金を請求するため
                        </p>
                        <p>
                            8. 上記の利用目的に付随する目的
                        </p>
                    </div>
                </div>
            </div>
        <br>
            <div class="card-body mb-4">
                <h4 class="card-title">
                    第4条（利用目的の変更）
                </h4>
                <div class="card-text ml-2">
                    <p>
                        1. 当社は、利用目的が変更前と関連性を有すると合理的に認められる場合に限り、個人情報の利用目的を変更するものとします。
                    </p>
                    <p>
                        2. 利用目的の変更を行った場合には、変更後の目的について、当社所定の方法により、ユーザーに通知し、または本ウェブサイト上に公表するものとします。
                    </p>
                </div>
            </div>
        <br>
            <div class="card-body mb-4">
                <h4 class="card-title">
                    第5条（個人情報の第三者提供）
                </h4>
                <div class="card-text">
                    <p>
                        1.当社は、次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。ただし、個人情報保護法その他の法令で認められる場合を除きます。
                    </p>
                    <div class="ml-2">
                        <p>
                            1. 人の生命、身体または財産の保護のために必要がある場合であって、本人の同意を得ることが困難であるとき
                        </p>
                        <p>
                            2. 公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき
                        </p>
                        <p>
                            3.
                            国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
                        </p>
                        <p>
                            4. 予め次の事項を告知あるいは公表し、かつ当社が個人情報保護委員会に届出をしたとき
                        </p>
                        <div class="ml-2">
                            <p>
                                1. 利用目的に第三者への提供を含むこと
                            </p>
                            <p>
                                2. 第三者に提供されるデータの項目
                            </p>
                            <p>
                                3. 第三者への提供の手段または方法
                            </p>
                            <p>
                                4. 本人の求めに応じて個人情報の第三者への提供を停止すること
                            </p>
                            <p>
                                5. 本人の求めを受け付ける方法
                            </p>
                        </div>
                    </div>
                    <p>
                        2. 前項の定めにかかわらず、次に掲げる場合には、当該情報の提供先は第三者に該当しないものとします。
                    </p>
                    <div class="ml-2">
                        <p>
                            1. 当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
                        </p>
                        <p>
                            2. 合併その他の事由による事業の承継に伴って個人情報が提供される場合
                        </p>
                        <p>
                            3.
                            個人情報を特定の者との間で共同して利用する場合であって、その旨並びに共同して利用される個人情報の項目、共同して利用する者の範囲、利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について、あらかじめ本人に通知し、または本人が容易に知り得る状態に置いた場合
                        </p>
                    </div>
                </div>
            </div>
        <br>
            <div class="card-body mb-4">
                <h4 class="card-title">
                    第6条（個人情報の開示）
                </h4>
                <div class="card-text">
                    <p>
                        1.
                        当社は、本人から個人情報の開示を求められたときは、本人に対し、遅滞なくこれを開示します。ただし、開示することにより次のいずれかに該当する場合は、その全部または一部を開示しないこともあり、開示しない決定をした場合には、その旨を遅滞なく通知します。なお、個人情報の開示に際しては、1件あたり1、000円の手数料を申し受けます。
                    </p>
                    <div class="ml-2">
                        <p>
                            1. 本人または第三者の生命、身体、財産その他の権利利益を害するおそれがある場合
                        </p>
                        <p>
                            2. 当社の業務の適正な実施に著しい支障を及ぼすおそれがある場合
                        </p>
                        <p>
                            3. その他法令に違反することとなる場合
                        </p>
                    </div>
                    <p class="card-text">
                        2. 前項の定めにかかわらず、履歴情報および特性情報などの個人情報以外の情報については、原則として開示いたしません。
                    </p>
                </div>
            </div>
        <br>
            <div class="card-body mb-4">
                <h4 class="card-title">
                    第7条（個人情報の訂正および削除）
                </h4>
                <div class="card-text">
                    <p>
                        1.
                        ユーザーは、当社の保有する自己の個人情報が誤った情報である場合には、当社が定める手続きにより、当社に対して個人情報の訂正、追加または削除（以下、「訂正等」といいます。）を請求することができます。
                    </p>
                    <p>
                        2. 当社は、ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の訂正等を行うものとします。
                    </p>
                    <p>
                        3. 当社は、前項の規定に基づき訂正等を行った場合、または訂正等を行わない旨の決定をしたときは遅滞なく、これをユーザーに通知します。
                    </p>
                </div>
            </div>
        <br>
            <div class="card-body mb-4">
                <h4 class="card-title">
                    第8条（個人情報の利用停止等）
                </h4>
                <div class="card-text">
                    <p>
                        1.
                        当社は、本人から、個人情報が、利用目的の範囲を超えて取り扱われているという理由、または不正の手段により取得されたものであるという理由により、その利用の停止または消去（以下、「利用停止等」といいます。）を求められた場合には、遅滞なく必要な調査を行います。
                    </p>
                    <p>
                        2. 前項の調査結果に基づき、その請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の利用停止等を行います。
                    </p>
                    <p>
                        3. 当社は、前項の規定に基づき利用停止等を行った場合、または利用停止等を行わない旨の決定をしたときは、遅滞なく、これをユーザーに通知します。
                    </p>
                    <p>
                        4.
                        前2項にかかわらず、利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって、ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は、この代替策を講じるものとします。
                    </p>
                </div>
            </div>
        <br>
            <div class="card-body mb-4">
                <h4 class="card-title">
                    第9条（プライバシーポリシーの変更）
                </h4>
                <div class="card-text">
                    <p>
                        1. 本ポリシーの内容は、法令その他本ポリシーに別段の定めのある事項を除いて、ユーザーに通知することなく、変更することができるものとします。
                    </p>
                    <p>
                        2. 当社が別途定める場合を除いて、変更後のプライバシーポリシーは、本ウェブサイトに掲載したときから効力を生じるものとします。
                    </p>
                </div>
            </div>
        <br>
            <div class="card-body">
                <h4 class="card-title">
                    第10条（お問い合わせ窓口）
                </h4>
                <div class="card-text">
                    <p>
                        本ポリシーに関するお問い合わせは、下記の窓口までお願いいたします。
                    </p>
                    <p>
                        管理者：Hayata Aoki
                    </p>
                    <p>
                        Eメールアドレス：hayata07130916@gmail.com
                    </p>
                </div>
                <p class="text-right">
                    以上
                </p>
            </div>
        </div>
    </div>

<%= render 'static_pages/footer' %>