config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/policy'
  get 'static_pages/terms'
  
  resources :guest_sessions, only: [:create]
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/index_room:id', to: 'rooms#index',as: 'index_room'
 
  get '/profile:id', to: 'users#profile',as: 'profile_user'
  get '/index:id', to: 'users#index',as: 'index'
  get '/follower:id', to: 'users#follower',as: 'follower'
  get '/following:id', to: 'users#following',as: 'following'
  get '/setting:id', to: 'users#setting',as: 'setting'
  get '/edit_prf:id', to: 'users#edit_prf',as: 'edit_prf'
  get '/favorite:id', to: 'users#favorite',as: 'favorite'
  get '/community_list:id', to: 'users#community_list',as: 'community_list'
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/send_message:id', to: 'rooms#send_message',as: 'send_message'
  get '/match:id', to: 'users#matcher',as: 'match'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms
  resources :messages, :only => [:create]
  resources :communities do
    resource :joins, only: [:create, :destroy]
  end
  
    get '/game:id', to: 'communities#game',as: 'game'
    get '/music:id', to: 'communities#music',as: 'music'
    get '/love:id', to: 'communities#love',as: 'love'
    get '/health:id', to: 'communities#health',as: 'health'
    get '/work:id', to: 'communities#work',as: 'work'
    get '/animal:id', to: 'communities#animal',as: 'animal'
    get '/sport:id', to: 'communities#sport',as: 'sport'
    get '/cafe:id', to: 'communities#cafe',as: 'cafe'
    get '/art:id', to: 'communities#art',as: 'art'
    get '/fashion:id', to: 'communities#fashion',as: 'fashion'
    get '/food:id', to: 'communities#food',as: 'food'
    get '/travel:id', to: 'communities#travel',as: 'travel'
    get '/info:id', to: 'communities#info',as: 'info'
  
  resources :users do
    member do
      get :following, :followers
    end
    get :joins, on: :collection
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :joins, dependent: :destroy
  has_many :communities,through: :joins
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  mount_uploader :image, ImageUploader
  
  attr_accessor :remember_token, :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest
  
  
  
  #ユーザー名は２文字以上、10文字以下
  validates :name,  presence: true, length: {maximum: 30}
  validates :content,  presence: false
  validates :tweet,  presence: false, length: {maximum: 40}
  
  #『メールアドレス関連』
  before_save { self.email = email.downcase } #認証前に全ての文字を小文字に変換
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  validates :email, presence: true, length: { maximum: 100 },
  format: { with: VALID_EMAIL_REGEX }, #フォーマットの検証
  uniqueness: true  #一意性の検証(大文字・小文字の区別)
  
  #『パスワード関連』
  has_secure_password #パスワードをハッシュ化
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{8,}\z/
  validates :password, presence: true,
  format: { with: VALID_PASSWORD_REGEX }, allow_nil: true
  
  validates :age,  presence: true
  
  enum sex: { 男性: 0, 女性: 1 }
  validates :sex,
    presence: true,
    inclusion: { in: proc { sexes.keys } }
    
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  

  def activate
    update_columns(activated: FILL_IN, activated_at: FILL_IN)
  end


  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  

  def follow(other_user)
    following << other_user
  end

 
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
  
  def matchers
    User.where(id: passive_relationships.select(:follower_id)).where(id: active_relationships.select(:followed_id))
  end
  
  
  def join(community)
    joins.find_or_create_by(community_id: community.id)
  end
  
  def not_join(community)
    joins.delete_by(community_id: community.id)
  end
  
 

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    
  
  enum Body_shape: { スリム: 0, やや細め: 1, 普通: 2, グラマー: 3, 筋肉質:4, ややぽっちゃり:5, ぽっちゃり:6 }, _prefix: true
  
  enum residence: {北海道:0,青森:1,岩手:2,宮城:3,秋田:4,山形:5,福島:6,
                    茨城:7,栃木:8,群馬:9,埼玉:10,千葉:11,東京:12,神奈川:13,
                    新潟:14,富山:15,石川:16,福井:17,山梨:18,長野:19,岐阜:20,
                    静岡:21,愛知:22,三重:23, 滋賀:24,京都:25,大阪:26,兵庫:27,
                   奈良:28,和歌山:29,鳥取:30,島根:31,岡山:32,広島:33,山口:34,
                    徳島:35,香川:36,愛媛:37,高知:38,福岡:39,佐賀:40,長崎:41,
                    熊本:42,大分:43,宮崎:44,鹿児島:45,沖縄:46 }, _prefix: true

  enum Birthplace: {北海道:0,青森:1,岩手:2,宮城:3,秋田:4,山形:5,福島:6,
                    茨城:7,栃木:8,群馬:9,埼玉:10,千葉:11,東京:12,神奈川:13,
                    新潟:14,富山:15,石川:16,福井:17,山梨:18,長野:19,岐阜:20,
                    静岡:21,愛知:22,三重:23, 滋賀:24,京都:25,大阪:26,兵庫:27,
                   奈良:28,和歌山:29,鳥取:30,島根:31,岡山:32,広島:33,山口:34,
                    徳島:35,香川:36,愛媛:37,高知:38,福岡:39,佐賀:40,長崎:41,
                    熊本:42,大分:43,宮崎:44,鹿児島:45,沖縄:46 }, _prefix: true
                    
  enum work: {上場企業:0,金融:1,公務員:2,コンサル:3,経営者・役員:4,大手企業:5,大手外資:6,
                    大手商社:7,外資金融:8,医師:9,看護師:10,薬剤師:11,弁護士:12,公認会計士:13,
                    パイロット:14,客室乗務員:15,広告:16,マスコミ:17,教育関連:18,IT関連:19,食品関連:20,
                    旅行関係:21,製薬:22,保険:23,不動産:24,建築関連:25,通信:26,流通:27,
                    WEB関連:28,ブライダル:29,クリエイター:30,接客業:31,受付:32,調理師・栄養士:33,アパレル・ショップ:34,
                    美容関係:35,エンターテインメント:36,アナウンサー:37,芸能・モデル:38,イベントコンパニオン:39,スポーツ選手:40,秘書:41,
                    事務員:42,福祉・介護:43,保育士:44,会社員:45,学生:46,自由業:47,税理士:48,
                    エンジニア:49,建築士:50,美容師:51,歯科医師:52,歯科衛生士:53,その他:54 }
                    
  enum holiday: {土日: 0, 平日: 1, 不定期: 2, その他: 3 }, _prefix: true
  
private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def favorite
    @user = User.find(params[:id])
  end
  
  def matcher
    @user = User.find(params[:id])
    @users = @user.matchers
    @followerUsers = @user.followers
  end
  
  def index
     if current_user.sex == "男性"
          @users = User.where(activated: true, sex: "女性")
          @q = User.ransack(params[:q])
          @users = @q.result(distinct: true).where(sex: "女性")
          @users = Kaminari.paginate_array(@users).page(params[:page]).per(30)
     elsif current_user.sex == "女性"
          @users = User.where(activated: true, sex: "男性")
          @q = User.ransack(params[:q])
          @users = @q.result(distinct: true).where(sex: "男性")
          @users = Kaminari.paginate_array(@users).page(params[:page]).per(30)
     end

  end
  
  def new
    
  end
  
  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
    
    if logged_in?
      @currentUserEntry = Entry.where(user_id: current_user.id)
      @userEntry = Entry.where(user_id: @user.id)
        unless @user.id == current_user.id
          @currentUserEntry.each do |cu|
            @userEntry.each do |u|
              if cu.room_id == u.room_id then
                @isRoom = true
                @roomId = cu.room_id
              end
            end
          end
          unless @isRoom
            @room = Room.new
            @entry = Entry.new
          end
        end
    end
  end
  
  def community_list
    @user = User.find(params[:id])
    @communities = @user.communities.where(category: 0)
    @communities2 = @user.communities.where(category: 1)
    @communities3 = @user.communities.where(category: 2)
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "アカウント認証メールを確認して登録を完了してください。"
      redirect_to root_url
    else
      render 'new'
    end
  end
  

  def edit
    @user = User.find(params[:id])
  end
  

  def update
    @user = User.find(params[:id])
    if @user.update(user_params2)
       redirect_to @user
    else
       render 'edit'
    end
  end
  
 def edit_prf
    @user = User.find(params[:id])
 end
 
 def profile
    @user = User.find(params[:id])
    @communities = @user.communities
 end
 
  #許可された値のみ取得{名前,メールアドレス,パスワード,パスワードの確認}
  private
    
   def user_params
      params.permit(:name, :email, :password,:password_confirmation, :sex, :age, :image)
   end
   
   def user_params2
      params.require(:user).permit(:name, :email, :password,:password_confirmation, :sex, :age, :image, :height,
                    :Body_shape, :blood_type, :residence, :Birthplace, :holiday, :work, :tweet, :content )
   end
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
   def search_params
      params.require(:q).permit!
   end
   
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_left_partial.erb
<div id="app-link">
<div class="side">
    
    <div style="margin-top:7%;">
      
      <div class="title-gem"><a href="/" class="fas fa-gem fa-xs">RailsApp</a></div>
    
    </div>
    <div class="container wrapper fixed-bottom">
          <ul class="row item-bar">
                <li><%= link_to "　さがす", index_path(current_user), {class: "fas fa-search"} %></li>
                <li><%= link_to "　メッセージ", index_room_path(current_user), {class: "fas fa-comment"} %></li>
                <li><%= link_to "　マッチング", match_path(current_user), {class: "fas fa-heart"} %></li>
                <li><%= link_to "　プロフィール", user_path(current_user), {class: "fas fa-user"} %></li>
                <li><%= link_to "　コミュニティ", community_path(current_user), {class: "fas fa-globe"} %></li>
                <%#= link_to "　つぶやき", tweet_path(current_user), {class: "fas fa-paw"} %>
                <li><%= link_to "　設定", setting_path(current_user), {class: "fas fa-cog"} %></li>
          </ul>
    </div>
</div> 
<div class="table_frame">
  <%= yield %>
</div>

</div>

               
               
              
                
         
             

app/views/users/community_list.html.erb
<%= render 'users/left_partial' %>
<div id="community-list" v-cloak>    
      <div class="main-contents">
          <h4 style="margin-left:20px; color:#505154;"><%= @user.name %>さんの参加コミュニティ</h4>
          <div class="item-bar3">
            <p v-on:click="change('A')" v-bind:class="{'active': isActive === 'A'}">趣味</p>
            <p v-on:click="change('B')" v-bind:class="{'active': isActive === 'B'}">ライフスタイル</p>
            <p v-on:click="change('C')" v-bind:class="{'active': isActive === 'C'}">価値観</p>
          </div>
          
          <div v-if="isActive === 'A'">
            <div class="community-grid " style="margin-left:41px; grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;">
              <% @communities.each do |c| %>
                <div class="community-info">
                   <%= link_to info_path(c) do %>
                     <%= image_tag c.image, class: "community_icon2"  %>
                     <p><%= c.name %></p>
                   <% end %>  
                </div>
              <% end %>
            </div>  
          </div>
          
          <div v-else-if="isActive === 'B'">
            <div class="community-grid " style="margin-left:41px; grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;">
              <% @communities2.each do |c| %>
                <div class="community-info">
                   <%= image_tag c.image, class: "community_icon2"  %>
                   <p><%= c.name %></p>
                </div>
              <% end %>
            </div>  
          </div>
          
          <div v-else-if="isActive === 'C'">
            <div class="community-grid " style="margin-left:41px; grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;">
              <% @communities3.each do |c| %>
                <div class="community-info">
                   <%= image_tag c.image, class: "community_icon2"  %>
                   <p><%= c.name %></p>
                </div>
              <% end %>
            </div>  
          </div>
          
          
      </div>
</div>

<script>
new Vue({
  el: '#community-list',
  data: {
    isActive: 'A'
  },
  methods: {
    change: function(num){
      this.isActive = num
    }
  }
})
</script>

app/views/users/index.html.erb
<style>
    [v-cloak] {
      display: none;
    }
</style>

<div id="app-users" v-cloak>
<%= render 'users/left_partial' %>
<div class="main-contents">
    <p style="font-size:2em; font-weight:bolder;">さがす</p>
      
          <div v-on:click="openModal"  class="fas fa-search search-name" id="search-form"></div>
              <div v-show="searchC" class="search-users">
                  <button v-on:click="closeModal" class="fas fa-times cross-icon"></button>
                  <div class="search-wrapper">
                    <%= render 'users/search' %>
                  </div>
              </div>
          
          
         <div class="user-grid " style="margin-left:41px;">
             <% @users.each do |user| %>
                 <%= link_to user_path(user), style: "cursor:default;", method: :get do %>
                    <ul class="user-info">
                      <div><%= image_tag user.image.url, class: "user_icon" %></div>
                          <li><p style="text-align:left;"><%= user.name[0, 5] + '...' %> <%= user.age %>歳 <%= user.residence %></p></li>
                    </ul>
                 <% end %>
                     
            <% end %>
            
            <%= paginate @users %>
            
            
         </div>
         
     </div>
</div>

  
<script>
        new Vue({
            el: '#app-users',
            data: {
                searchC : false,
                html : false
            },
            methods: {
                        openModal: function () {
                            this.searchC = true
                        },
                        closeModal: function () {
                            this.searchC = false
                        }
                        
                     }
                     
        });
        
        
</script>
  

app/views/users/matcher.html.erb
<%= render 'users/left_partial' %>
    <div class="main-contents">
        
        <div id="tabContents">
            <div class="item-bar3">
                <p v-on:click="change('A')" v-bind:class="{'active': isActive === 'A'}">マッチング中</p>
                <p v-on:click="change('B')" v-bind:class="{'active': isActive === 'B'}">お相手から</p>
            </div>
        
      
        
        <div v-if="isActive === 'A'" style="border-top-style: solid; border-width:1px; border-color:#ebeef2;">
            <% @users.each do |user| %>
            
            <div style="margin-left:41px; margin-top:10px;"><%= image_tag user.image_url, class: "user_icon4" %></div>
                <ul class="user-info-2">
                    <li><p><%= user.name %></p></li>
                    <li><p><%= user.age %>歳 <%= user.residence %></p></li>
                </ul>
            <div class="button-contents-msg">
                <%= link_to 'プロフィール詳細', user_path(user), method: :get, class: "detail-user-button shadow" %>
            </div>
     
        <% end %>
        </div>
    
    
    
        <div v-else-if="isActive === 'B'" style="overflow: hidden; border-top-style: solid; border-width:1px; border-color:#ebeef2;">
            <% @followerUsers.each do |user| %>
            <div style="margin-left:41px; margin-top:10px;"><%= image_tag user.image_url, class: "user_icon4" %></div>
                <ul class="user-info-2">
                    <li><p><%= user.name %></p></li>
                    <li><p><%= user.age %>歳 <%= user.residence %></p></li>
                </ul>
            <div class="button-contents-msg2">
                <div id="favorite_form">
                <% if current_user.following?(user) %>
                    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),
                          html: { method: :delete }, remote: true) do |f| %>
                         <%= f.submit "いいね！を解除", class: "detail-user-button2", id: "no-follow" ,style: "width:130px;" %>
                      <% end %>
                  <% else %>
                      <%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
                          <div><%= hidden_field_tag :followed_id, user.id %></div>
                         <%= f.submit "いいね！を送信", class: "detail-user-button2", id: "yes-follow" ,style: "width:130px; background:#29f2bd;" , onMouseOver: "this.style.background='#3ad6a2'", onMouseOut: "this.style.background='#29f2bd'" %>
                      <% end %>
                <% end %>
                </div>
                
            </div>
        <% end %>
        </div>
 
      </div>
      
    </div>
    
<script>
new Vue({
  el: '#tabContents',
  data: {
    isActive: 'A'
  },
  methods: {
    change: function(num){
      this.isActive = num
    }
  }
})
</script>

app/views/users/setting.html.erb
<%= render 'users/left_partial' %>

<div class="main-contents">
  <ul>    
    <li><%= button_to "ログアウト", logout_path, url: root_url, method: :delete %></li>
  </ul>
</div>

app/views/users/show.html.erb
<%= render 'users/left_partial' %>
  <div id="app-1" v-cloak>    
      <div class="main-contents">
         <div style="margin-left:20px;"> 
          
          <div v-if="isActive === 'A'">
              <div class="icon-prf">
                 <% if @user.image? %>
                    <%= image_tag @user.image.url, class: "user_icon2" %>
                <% else %>
                    <%= image_tag "default_icon.jpg", class: "user_icon2" %>
                <% end %>
              </div>
              
              <p style="text-align:center; margin:20px;"><%= content_tag :span, @user.name, class: "username" %></p>
              <div style="display:flex; justify-content:center;">
                <div id="favorite_form" style="margin-bottom:20px; display:flex; justify-content:center;">
                  <% if current_user == @user %>
                        <span></span>
                  <% else %>
                    <% if current_user.following?(@user) %>
                    <%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
                          html: { method: :delete }, remote: true) do |f| %>
                         <%= f.submit "いいね！を解除", id: "no-follow" , class: "detail-user-button2" ,style: "width:130px;" %>
                    <% end %>
                    
                    <br>
                   <% if logged_in? %>
                     <% unless @user.id == current_user.id %>
                       <% if @isRoom == true %>
                          <%= link_to room_path(@roomId) do %>
                              <button class="detail-user-button shadow" type="submit" id="send_message-s">メッセージを送る</button>
                          <% end %>
                       <% else %>
                          
                         <%= form_for @room, url: rooms_path do |f| %>
                            <%= fields_for @entry do |e| %>
                               <%= e.hidden_field :user_id, :value=> @user.id %>
                            <% end %>
                          <button class="detail-user-button shadow" type="submit" id="send_message-s">メッセージを送る</button>
                         <% end %>
                       <% end %>
                     <% end %>
                   <% end %>
                    
                    <% else %>
                    <%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
                        <div><%= hidden_field_tag :followed_id, @user.id %></div>
                       <%= f.submit "いいね！を送信",id: "yes-follow" , class: "detail-user-button2" ,style: "width:130px; background:#29f2bd;" , onMouseOver: "this.style.background='#3ad6a2'", onMouseOut: "this.style.background='#29f2bd'" %>
                    <% end %> 
                    
                  <% end %>  
                  <% end %>
                
                </div>
                
            </div>
              
              
              <div>
                <% if @user.tweet == nil %>
                  <% if @user.content == nil %>
                    <p></p>
                  <% else %>  
                    <strong><p style="text-align:center;"><%= @user.content[0, 30] + '...' %></p></strong>
                  <% end %>
                <% elsif @user.tweet.present? %>
                  <strong ><p style="text-align:center;"><%= @user.tweet %></p></strong>
                <% end %>
              </div>
              
              <div style="border-top: solid 2px #b8b2b2;">
                <h3 style="font-weight:bold; margin-left:20px;">参加コミュニティ</h3>
                <% if @user.communities.present? %>
                <p style="margin-top:40px;text-align:center; font-size:20px; font-weight:bold; text-decoration: none; "><%= link_to "すべてを見る" ,community_list_path %></p>
                  <div class="table-responsive" style="margin-top:30px;">
                    <table>
                      <div class="community-grid " style="margin-left:41px; grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;">
                        <% @user.communities.each do |c| %>
                          <div class="community-info">
                             <%= link_to info_path(c) do %>
                               <%= image_tag c.image, class: "community_icon"  %>
                               <p><%= c.name %></p>
                             <% end %>
                          </div>
                        <% end %>
                      </div>
                   </table>
                  </div>
                <% else %>
                  <p style="font-size:2em; font-weight:bold; margin-top:80px; text-align:center;">コミュニティはまだありません</p>
                  <% if current_user == @user %>
                     <div class="button-contents">
                        <div><%= button_to 'コミュニティを探す', community_path, method: :get ,class: "today shadow" %></div>
                    </div>
                  <% end %>
                <% end %>
                    
              </div>
          </div>
            
          <div v-else-if="isActive === 'B'">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">/</th>
                    <th scope="col">基本プロフィール</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">名前</th>
                    <td><%= @user.name %></td>
                  </tr>
                  <tr>
                    <th scope="row">年齢</th>
                    <td><%= @user.age %>歳</td>
                  </tr>
                  <tr>
                    <th scope="row">血液型</th>
                    <td><%= @user.residence %></td>
                  </tr>
                  <tr>
                    <th scope="row">出身地</th>
                    <td><%= @user.Birthplace %></td>
                  </tr>
                </tbody>
              </table>
            
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">/</th>
                    <th scope="col">プロフィール項目</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">身長</th>
                    <td><%= @user.height %>cm</td>
                  </tr>
                  <tr>
                    <th scope="row">体型</th>
                    <td><%= @user.Body_shape %></td>
                  </tr>
                  <tr>
                    <th scope="row">血液型</th>
                    <td><%= @user.blood_type %></td>
                  </tr>
                  <tr>
                    <th scope="row">職業</th>
                    <td><%= @user.work %></td>
                  </tr>
                  <tr>
                    <th scope="row">休日</th>
                    <td><%= @user.holiday %></td>
                  </tr>
                </tbody>
              </table>
              <h4 style="font-weight:bold; margin-left:5px;">自己紹介文</h3>
              <p style="text-align:center;"><%= @user.content %></p>
          </div>
          
          
          <div v-else-if="isActive === 'C'">
             <%= render 'users/edit_prf'%>
          </div>
          
          
      </div>
      
      
     </div>
    
    <div class="header-menu-prf" style="margin-left:29%;">
      <ul class="icon-prf2">
          <li v-on:click="change('A')" v-bind:class="{'active': isActive === 'A'}">
          <i v-bind:class="{'active': isActive === 'A'}" class="fas fa-street-view fa-4x"></i>
          <p v-bind:class="{'active': isActive === 'A'}" style="text-align: center;">Intro</p>
          </li>
          
          <li v-on:click="change('B')" v-bind:class="{'active': isActive === 'B'}" style="margin-left:20%;">
          <i v-bind:class="{'active': isActive === 'B'}" class="fas fa-id-card fa-4x"></i>
          <p v-bind:class="{'active': isActive === 'B'}" style="text-align: center;">Profile</p>
          </li>
          
          <% if current_user == @user %>
          <li v-on:click="change('C')" v-bind:class="{'active': isActive === 'C'}" style="margin-left:20%;">
          <i v-bind:class="{'active': isActive === 'C'}" class="fas fa-edit fa-4x"></i>
          <p v-bind:class="{'active': isActive === 'C'}" style="text-align: center; padding-right:10px;">Edit</p>
          </li>
          <% end %>
          
      </ul>
    </div>
  </div>
<script>
new Vue({
  el: '#app-1',
  data: {
    isActive: 'A'
  },
  methods: {
    change: function(num){
      this.isActive = num
    }
  }
})
</script>