config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/policy'
  get 'static_pages/terms'
  
  resources :guest_sessions, only: [:create]
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/index_room:id', to: 'rooms#index',as: 'index_room'
 
  get '/profile:id', to: 'users#profile',as: 'profile_user'
  get '/index:id', to: 'users#index',as: 'index'
  get '/follower:id', to: 'users#follower',as: 'follower'
  get '/following:id', to: 'users#following',as: 'following'
  get '/setting:id', to: 'users#setting',as: 'setting'
  get '/edit_prf:id', to: 'users#edit_prf',as: 'edit_prf'
  get '/favorite:id', to: 'users#favorite',as: 'favorite'
  get '/community_list:id', to: 'users#community_list',as: 'community_list'
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/send_message:id', to: 'rooms#send_message',as: 'send_message'
  get '/match:id', to: 'users#matcher',as: 'match'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms
  resources :messages, :only => [:create]
  resources :communities do
    resource :joins, only: [:create, :destroy]
  end
  
    get '/game:id', to: 'communities#game',as: 'game'
    get '/music:id', to: 'communities#music',as: 'music'
    get '/love:id', to: 'communities#love',as: 'love'
    get '/health:id', to: 'communities#health',as: 'health'
    get '/work:id', to: 'communities#work',as: 'work'
    get '/animal:id', to: 'communities#animal',as: 'animal'
    get '/sport:id', to: 'communities#sport',as: 'sport'
    get '/cafe:id', to: 'communities#cafe',as: 'cafe'
    get '/art:id', to: 'communities#art',as: 'art'
    get '/fashion:id', to: 'communities#fashion',as: 'fashion'
    get '/food:id', to: 'communities#food',as: 'food'
    get '/travel:id', to: 'communities#travel',as: 'travel'
    get '/info:id', to: 'communities#info',as: 'info'
  
  resources :users do
    member do
      get :following, :followers
    end
    get :joins, on: :collection
  end


end

app/models/room.rb
class Room < ApplicationRecord
   has_many :entries, dependent: :destroy
   has_many :messages, dependent: :destroy
   has_many :users, through: :entries
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    
    def send_message
      @user = User.find(params[:id])
      if logged_in?
            #Entry内のuser_idがcurrent_userと同じEntry
            @currentUserEntry = Entry.where(user_id: current_user.id)
            #Entry内のuser_idがMYPAGEのparams.idと同じEntry
            @userEntry = Entry.where(user_id: @user.id)
                #@user.idとcurrent_user.idが同じでなければ
                unless @user.id == current_user.id
                  @currentUserEntry.each do |cu|
                    @userEntry.each do |u|
                      #もしcurrent_user側のルームidと＠user側のルームidが同じであれば存在するルームに飛ぶ
                      if cu.room_id == u.room_id then
                        @isRoom = true
                        @roomId = cu.room_id
                      end
                    end
                  end
                  #ルームが存在していなければルームとエントリーを作成する
                  unless @isRoom
                    @room = Room.new
                    @entry = Entry.new
                  end
                end
      end
    end
    
    
    def index
      @user = current_user
      @currentEntries = current_user.entries
      #@currentEntriesのルームを配列にする
      myRoomIds = []
      @currentEntries.includes([:room]).each do |entry|
        myRoomIds << entry.room.id
      end
      #@currentEntriesのルーム且つcurrent_userでないEntryを新着順で取ってくる
      @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: @user.id).order(created_at: :desc)
    end
    
    def show
      @room = Room.find(params[:id])
        if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
          @messages = @room.messages.includes(:user)
          @message = Message.new
          @entries = @room.entries.includes(:user)
        else
          redirect_back(fallback_location: root_path)
        end

    end
    
    def create
      @room = Room.create
      #entryにログインユーザーを作成
      @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
      #entryにparamsユーザーを作成
      @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
      redirect_to room_path(@room.id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<%= render 'users/left_partial' %>
<div class="main-contents">
<h2>メッセージ一覧</h2>
<% if @anotherEntries.empty? %>
  <div style="margin-top:30px;">
    <p style="text-align:center; font-size:30px;">メッセージがありません</p>
    <div style="display:flex; justify-content:center;">
        <%= link_to 'マッチングしたお相手にメッセージ', match_path(current_user), method: :get, class: "detail-user-button shadow" ,id: "send_message-s", style: "padding-top:30px; padding-bottom:30px; font-size:20px;" %>
    </div>
  </div>
<% else %>
<% @anotherEntries.includes([:room],[:user]).each do |e| %>
    <table class="table table-striped">
        <tr>
            <td>
　　　　　　　　　<!-- 名前からroomの詳細に飛べるようにリンク化 -->
                <%= link_to room_path(e.room.id) do %>
                    <%= image_tag e.user.image.url, class: "room_icon" %>
                    <%= e.user.name %>
                <% end %>
            </td>
            <td>
               <!-- 最新メッセージ内容の最初の7文字を表示する -->
                <%# dm = Message.find_by(id: e.room.message_ids.last).content %>
                <%#= truncate(dm, length: 10) %>
            </td>
            <td>
                <h6 style="color: #C0C0C0;"><%= e.updated_at.strftime("%Y/%m/%d %H:%M") %></h6>
            </td>
            <td>
               <!-- ゴミ箱アイコンクリックでroomを消せるようにする -->
                <%= link_to room_path(e.room.id), method: :delete do %>
                    <i class="fas fa-trash" style="color: black;"></i>
                <% end %>
            </td>
        </tr>
    </table>
  <% end %>
<% end %>
</div>

app/views/rooms/send_message.html.erb
<body style="background-color: rgba(0,0,0,0.6);">
    <div class="user-contents"> 
        <div><%= image_tag @user.image.url, class: "user_icon5" %></div>
        <div class="user-info-3">
              <p><%= @user.name %></p>
              <p><%= @user.residence %></p>
              <p><%= @user.age %>歳</p>
        </div>
        
        <div style="display:flex; justify-content:center;">
        <% if logged_in? %>
          <% unless @user.id == current_user.id %>
             <% if @isRoom == true %>
                <%= link_to room_path(@roomId) do %>
                    <button id="dm_submit">メッセージを送る</button>
                <% end %>
             <% else %>
                
             <%= form_for @room, url: rooms_path do |f| %>
                <%= fields_for @entry do |e| %>
                   <%= e.hidden_field :user_id, :value=> @user.id %>
                <% end %>
                <button type="submit" id="dm_submit">メッセージを送る</button>
             <% end %>
            <% end %>
          <% end %>
        <% end %>
        </div>
    </div>
</body>

app/views/rooms/show.html.erb
<%= render 'users/left_partial' %>
     <div class="main-contents">
         <div class="message-contents" id="app-messages">
        <div style="margin-left:1%;">
            <% @entries.includes([:user]).each do |e| %>
               <!-- eachで回したentryユーザーがログインユーザーであれば、@classに"current_user"の文字列を代入する。ログインユーザーであれば、空白を代入する -->
                <% current_user == e.user ? @class = "current_user" : @class = ""  %>
                   <!-- eachで回したentryユーザーがログインユーザーでなければ、entryユーザー名を表示する -->
                    <% if e.user != current_user %>
                       <h5 class="text-left <%= @class %>" id="<%= @class %>" style="font-size: 30px;" data-id="<%= e.user.id %>"><%= link_to "@#{e.user.name}", user_path(e.user_id) %></h5>
                    <% else %>
                       <h5 class="text-left <%= @class %>" id="<%= @class %>" data-id="<%= e.user.id %>"></h5>
                    <% end %>
            <% end %>
        <!-- メッセージ内容は、パーシャルにします -->
            <div id="messages" data-room_id="<%= @room.id %>">
                <%= render "messages/message" %>
            </div>
        </div>
        
     </div>
     
    </div>
     
     
        <div class="form-message">
            <%= form_with(model: @message, remote: true) do |f| %>
                <div>
                  <%= f.label :content,"新規メッセージを作成"  %>
                  <%= f.text_area :content, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-text-field" %>
                  <%= f.hidden_field :room_id, value: @room.id %>
                </div>
            <div style="width:100px; margin-left:80%;">
            <%= f.submit '送信',class: "detail-user-button", style: "font-size:15px;" %>
            <% end %>
            </div>
        </div>
     
<script>
    //トークルーム遷移時に入力フォーム記載場所にスクロールする(最新トークは下にあるため)
    let element = document.getElementById('target'); // 移動させたい位置の要素を取得
    let rect = element.getBoundingClientRect();
    let position = rect.top;
    setTimeout(() => {
    scrollTo(0, position);},
    1000)
</script>