config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/policy'
  get 'static_pages/terms'
  
  resources :guest_sessions, only: [:create]
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/index_room:id', to: 'rooms#index',as: 'index_room'
 
  get '/profile:id', to: 'users#profile',as: 'profile_user'
  get '/index:id', to: 'users#index',as: 'index'
  get '/follower:id', to: 'users#follower',as: 'follower'
  get '/following:id', to: 'users#following',as: 'following'
  get '/setting:id', to: 'users#setting',as: 'setting'
  get '/edit_prf:id', to: 'users#edit_prf',as: 'edit_prf'
  get '/favorite:id', to: 'users#favorite',as: 'favorite'
  get '/community_list:id', to: 'users#community_list',as: 'community_list'
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/send_message:id', to: 'rooms#send_message',as: 'send_message'
  get '/match:id', to: 'users#matcher',as: 'match'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms
  resources :messages, :only => [:create]
  resources :communities do
    resource :joins, only: [:create, :destroy]
  end
  
    get '/game:id', to: 'communities#game',as: 'game'
    get '/music:id', to: 'communities#music',as: 'music'
    get '/love:id', to: 'communities#love',as: 'love'
    get '/health:id', to: 'communities#health',as: 'health'
    get '/work:id', to: 'communities#work',as: 'work'
    get '/animal:id', to: 'communities#animal',as: 'animal'
    get '/sport:id', to: 'communities#sport',as: 'sport'
    get '/cafe:id', to: 'communities#cafe',as: 'cafe'
    get '/art:id', to: 'communities#art',as: 'art'
    get '/fashion:id', to: 'communities#fashion',as: 'fashion'
    get '/food:id', to: 'communities#food',as: 'food'
    get '/travel:id', to: 'communities#travel',as: 'travel'
    get '/info:id', to: 'communities#info',as: 'info'
  
  resources :users do
    member do
      get :following, :followers
    end
    get :joins, on: :collection
  end


end

app/models/community.rb
class Community < ApplicationRecord
    belongs_to :user, optional: true
    has_many :joins, dependent: :destroy   
    
    validates :name,  presence: true, length: {maximum: 30}
    validates :content,  presence: false, length: {maximum: 200}
    validates :category,  presence: true
    validates :genre,  presence: true
    
    enum category: {趣味:0,ライフスタイル:1,価値観:2}, _prefix: true
    enum genre: {ゲーム:0,音楽:1,恋愛・結婚:2,美容・健康:3,仕事:4,ペット・動物:5,スポーツ:6,カフェ:7,
                 アート:8,ファッション:9,フード・お酒:10,旅行:11}
    
    def joined_by?(user)
     joins.where(user_id: user).exists?
    end
    
    def unjoined_by?(user)
     joins.where(user_id: user).empty?
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  
    def index
       @communities = Community
       @q = Community.ransack(params[:q])
       @communities = @q.result(distinct: true)
    end
    
    def show
       @q = Community.ransack(params[:q])
    end
    
    def create
       @community = Community.new(community_params)
       @community.save
    end
    
    def info
      @user = current_user
      @community = Community.find(params[:id])
      @users = @community.joins.includes([:user]).map{|join| join.user}
      #@users = @users.find(sex: 0)
      
    end
    
    def game 
      @communities = Community.where(genre: 0 )
      
    end
    def music 
      @communities = Community.where(genre: 1 )
    end
    def love
      @communities = Community.where(genre: 2 )
    end
    def health
      @communities = Community.where(genre: 3 )
    end
    def work
      @communities = Community.where(genre: 4 )
    end
    def animal
      @communities = Community.where(genre: 5 )
    end
    def sport
      @communities = Community.where(genre: 6 )
    end
    def cafe
      @communities = Community.where(genre: 7 )
    end
    def art
      @communities = Community.where(genre: 8 )
    end
    def fashion
      @communities = Community.where(genre: 9 )
    end
    def food
      @communities = Community.where(genre: 10 )
    end
    def travel
      @communities = Community.where(genre: 11 )
    end
  
      
  private  
    
    def community_params
      params.require(:community).permit(:content, :name, :image, :category, :genre)
    end
    
    def set_q
    @q = Community.ransack(params[:q])
    end
    
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_parts.html.erb
<%= render 'users/left_partial' %>
<div class="main-contents">
    <h2 style="font-weight:bold;">コミュニティ</h2>
    <div class="community-grid " style="margin-left:41px;">
    <% @communities.each do |community| %>
    <%= link_to info_path(community), method: :get do %>
    <div class="community-info">
        <% if community.image? %>
            <div><%= image_tag community.image, class: "community_icon" %></div>
        <% else %>
            <div><%= image_tag "default_icon.jpg", class: "community_icon" %></div>
        <% end %>
        <p><%= community.name %></p>
        </div>
        <% end %>
    <% end %>
    </div>
</div>

app/views/communities/animal.html.erb
<%= render 'communities/parts' %>

app/views/communities/cafe.html.erb
<%= render 'communities/parts' %>

app/views/communities/fashion.html.erb
<%= render 'communities/parts' %>

app/views/communities/food.html.erb
<%= render 'communities/parts' %>

app/views/communities/game.html.erb
<%= render 'communities/parts' %>

app/views/communities/health.html.erb
<%= render 'communities/parts' %>

app/views/communities/index.html.erb
<%= render 'users/left_partial' %>
<div class="main-contents">
    <form class="community_search" id="community_search" action="/communities" accept-charset="UTF-8" method="get">
      <div class="row">
          <div class="col-xs-8">
          　<input placeholder="search" class="input-lg" type="search" name="q[name_cont]" id="q_name_cont" v-model="textbox" />
          </div>
      </div>
    </form> 
    <h2 style="font-weight:bold; margin-left:20px;">コミュニティ</h2>
    <div class="community-grid " style="margin-left:41px;">
    <% @communities.each do |community| %>
    <%= link_to info_path(community), method: :get do %>
    <div class="community-info">
        <% if community.image? %>
            <div><%= image_tag community.image, class: "community_icon" %></div>
        <% else %>
            <div><%= image_tag "default_icon.jpg", class: "community_icon" %></div>
        <% end %>
        <p><%= community.name %></p>
        </div>
        <% end %>
    <% end %>
    </div>
</div>

app/views/communities/info.html.erb
<%= render 'users/left_partial' %>
<div class="main-contents">
   <div> 
    <%= image_tag @community.image, class: "community_icon"  %>
    <div><strong style="font-size:20px;"><%= @community.name %></strong></div>
    
    <% if @community.joined_by?(current_user) %>
        <div style="padding-top:20px;"><%= link_to "このコミュニティから退会する", community_joins_path(community_id: @community.id), method: :delete, local: true, class: "detail-user-button2" %></div>
    <% else %>
        <div style="padding-top:20px;"><%= link_to "このコミュニティに参加する", community_joins_path(community_id: @community.id), method: :post, local: true, class: "detail-user-button2", style: "background: #348ceb;" %></div>
    <% end %>
   </div>
<br>
    <h3 style="margin-left:20px; color:#505154;">このコミュニティの参加者</h3>
    <div class="user-grid " style="margin-left:41px;">
         <% @users.each do |user| %>
             <% if user.sex == "女性"  %>
             <%= link_to user_path(user), method: :get do %>
                <ul class="user-info">
                  <div><%= image_tag user.image.url, class: "user_icon" , style:"cursor:pointer;" %></div>
                      <li><p style="text-align:left;"><%= user.name[0, 5] + '...' %> <%= user.age %>歳 <%= user.residence %></p></li>
                </ul>
             <% end %>
             <% end %>    
        <% end %>
    </div>
</div>

app/views/communities/love.html.erb
<%= render 'communities/parts' %>

app/views/communities/show.html.erb
<%= render 'users/left_partial' %>
<div id="community" v-cloak>    
    <div class="main-contents">
        <div style="margin-left:20px;">
            <form class="community_search" id="community_search" action="/communities" accept-charset="UTF-8" method="get">
              <div class="row">
                  <div class="col-xs-8">
                  <input placeholder="search" class="input-lg" type="search" name="q[name_cont]" id="q_name_cont" v-model="textbox" />
                  </div>
              </div>
            </form> 
            <h2 style="font-weight:bold;">コミュニティ</h2>
            
        </div>
        <br>
        <h3 style="font-weight:bold; margin-left:20px;">おすすめ</h3>
        <br>
        <h3 style="font-weight:bold; margin-left:20px;">カテゴリー</h3>
        <div class="community-grid " style="margin-left:41px;">
             <div class="community-info">
                 <div><%= link_to image_tag('game.jpg', class: "community_icon"), game_path(current_user)  %></div>
                 <p>ゲーム</p>
             </div>
             <div class="community-info"> 
                 <div><%= link_to  image_tag('music.jpg', class: "community_icon"), music_path(current_user)  %></div>
                 <p>音楽</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('love.jpg', class: "community_icon"), love_path(current_user) %></div>
                 <p>恋愛・結婚</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('health.jpg', class: "community_icon"), health_path(current_user) %></div>
                 <p>美容・健康</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('work', class: "community_icon"), work_path(current_user) %></div>
                 <p>仕事</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('animal.jpg', class: "community_icon"), animal_path(current_user)  %></div>
                 <p>ペット・動物</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('sport.jpg', class: "community_icon"), sport_path(current_user) %></div>
                 <p>スポーツ</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('cafe.jpg', class: "community_icon"), cafe_path(current_user) %></div>
                 <p>カフェ</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('art.jpg', class: "community_icon"), art_path(current_user) %></div>
                 <p>アート</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('fashion', class: "community_icon"), fashion_path(current_user) %></div>
                 <p>ファッション</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('food.jpg', class: "community_icon"), food_path(current_user)  %></div>
                 <p>フード・お酒</p>
             </div>
             <div class="community-info">
                 <div><%= link_to image_tag('travel.jpg', class: "community_icon"), travel_path(current_user) %></div>
                 <p>旅行</p>
             </div>
        </div>
    </div>
    
</div>

app/views/communities/sport.html.erb
<%= render 'communities/parts' %>

app/views/communities/travel.html.erb
<%= render 'communities/parts' %>

app/views/communities/work.html.erb
<%= render 'communities/parts' %>